# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: git submodule update --init --recursive

      # run tests!
      - run: cd DJ-core
      - run: mvn install -DskipTests
      - run: cd ..
      - run: cd mnist-reader
      - run: mvn install -DskipTests
      - run: cd ..
      - run: mvn test

